version: '3.8'

services:
  ml-service-test:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENV=testing
      - MODEL_NAME=all-MiniLM-L6-v2
    volumes:
      - .:/app
    command: pytest tests/
